#!/usr/bin/env bash

set -Eeuo pipefail

pushd "$(dirname "$0")" >/dev/null

bin_path="$(cargo build --profile release-with-debug --message-format=json | jq -r '.executable | select(. != null)')"
ln -fsv "$bin_path" ./run

popd >/dev/null
