AggregateError
Array
Array.from
Array.isArray
Array.of
Array.prototype.at
Array.prototype.concat
Array.prototype.copyWithin
Array.prototype.entries
Array.prototype.every
Array.prototype.fill
Array.prototype.filter
Array.prototype.find
Array.prototype.findIndex
Array.prototype.findLast
Array.prototype.findLastIndex
Array.prototype.flat
Array.prototype.flatMap
Array.prototype.forEach
Array.prototype.group
Array.prototype.groupToMap
Array.prototype.includes
Array.prototype.indexOf
Array.prototype.join
Array.prototype.keys
Array.prototype.lastIndexOf
Array.prototype.map
Array.prototype.pop
Array.prototype.push
Array.prototype.reduce
Array.prototype.reduceRight
Array.prototype.reverse
Array.prototype.shift
Array.prototype.slice
Array.prototype.some
Array.prototype.sort
Array.prototype.splice
Array.prototype.toLocaleString
Array.prototype.toString
Array.prototype.unshift
Array.prototype.values
ArrayBuffer
ArrayBuffer.isView
ArrayBuffer.prototype.slice
Atomics
Atomics.add
Atomics.and
Atomics.compareExchange
Atomics.exchange
Atomics.isLockFree
Atomics.load
Atomics.notify
Atomics.or
Atomics.store
Atomics.sub
Atomics.wait
Atomics.waitAsync
Atomics.xor
BigInt
BigInt.asIntN
BigInt.asUintN
BigInt.prototype.toLocaleString
BigInt.prototype.toString
BigInt.prototype.valueOf
BigInt64Array(TypedArray)
BigUint64Array(TypedArray)
Boolean
Boolean.prototype.toString
Boolean.prototype.valueOf
DataView
DataView.prototype.getBigInt64
DataView.prototype.getBigUint64
DataView.prototype.getFloat32
DataView.prototype.getFloat64
DataView.prototype.getInt16
DataView.prototype.getInt32
DataView.prototype.getInt8
DataView.prototype.getUint16
DataView.prototype.getUint32
DataView.prototype.getUint8
DataView.prototype.setBigInt64
DataView.prototype.setBigUint64
DataView.prototype.setFloat32
DataView.prototype.setFloat64
DataView.prototype.setInt16
DataView.prototype.setInt32
DataView.prototype.setInt8
DataView.prototype.setUint16
DataView.prototype.setUint32
DataView.prototype.setUint8
Date
Date.now
Date.parse
Date.prototype.getDate
Date.prototype.getDay
Date.prototype.getFullYear
Date.prototype.getHours
Date.prototype.getMilliseconds
Date.prototype.getMinutes
Date.prototype.getMonth
Date.prototype.getSeconds
Date.prototype.getTime
Date.prototype.getTimezoneOffset
Date.prototype.getUTCDate
Date.prototype.getUTCDay
Date.prototype.getUTCFullYear
Date.prototype.getUTCHours
Date.prototype.getUTCMilliseconds
Date.prototype.getUTCMinutes
Date.prototype.getUTCMonth
Date.prototype.getUTCSeconds
Date.prototype.getYear
Date.prototype.setDate
Date.prototype.setFullYear
Date.prototype.setHours
Date.prototype.setMilliseconds
Date.prototype.setMinutes
Date.prototype.setMonth
Date.prototype.setSeconds
Date.prototype.setTime
Date.prototype.setUTCDate
Date.prototype.setUTCFullYear
Date.prototype.setUTCHours
Date.prototype.setUTCMilliseconds
Date.prototype.setUTCMinutes
Date.prototype.setUTCMonth
Date.prototype.setUTCSeconds
Date.prototype.setYear
Date.prototype.toDateString
Date.prototype.toISOString
Date.prototype.toJSON
Date.prototype.toLocaleDateString
Date.prototype.toLocaleString
Date.prototype.toLocaleTimeString
Date.prototype.toString
Date.prototype.toTimeString
Date.prototype.toUTCString
Date.prototype.valueOf
Date.UTC
decodeURI
decodeURIComponent
encodeURI
encodeURIComponent
Error
Error.prototype.toString
escape
eval
EvalError
FinalizationRegistry
FinalizationRegistry.prototype.register
FinalizationRegistry.prototype.unregister
Float32Array(TypedArray)
Float64Array(TypedArray)
Function
Function.prototype.apply
Function.prototype.bind
Function.prototype.call
Function.prototype.toString
globalThis
Infinity
Int16Array(TypedArray)
Int32Array(TypedArray)
Int8Array(TypedArray)
Intl
Intl.Collator
Intl.Collator.prototype.compare
Intl.Collator.prototype.resolvedOptions
Intl.Collator.supportedLocalesOf
Intl.DateTimeFormat
Intl.DateTimeFormat.prototype.format
Intl.DateTimeFormat.prototype.formatRange
Intl.DateTimeFormat.prototype.formatRangeToParts
Intl.DateTimeFormat.prototype.formatToParts
Intl.DateTimeFormat.prototype.resolvedOptions
Intl.DateTimeFormat.supportedLocalesOf
Intl.getCanonicalLocales
Intl.ListFormat
Intl.ListFormat.prototype.format
Intl.ListFormat.prototype.formatToParts
Intl.ListFormat.prototype.resolvedOptions
Intl.ListFormat.supportedLocalesOf
Intl.NumberFormat
Intl.NumberFormat.prototype.format
Intl.NumberFormat.prototype.formatRange
Intl.NumberFormat.prototype.formatRangeToParts
Intl.NumberFormat.prototype.formatToParts
Intl.NumberFormat.prototype.resolvedOptions
Intl.NumberFormat.supportedLocalesOf
Intl.PluralRules
Intl.PluralRules.prototype.resolvedOptions
Intl.PluralRules.prototype.select
Intl.PluralRules.prototype.selectRange
Intl.PluralRules.supportedLocalesOf
Intl.RelativeTimeFormat
Intl.RelativeTimeFormat.prototype.format
Intl.RelativeTimeFormat.prototype.formatToParts
Intl.RelativeTimeFormat.prototype.resolvedOptions
Intl.RelativeTimeFormat.supportedLocalesOf
Intl.Segmenter
Intl.Segmenter.prototype.resolvedOptions
Intl.Segmenter.prototype.segment
Intl.Segmenter.supportedLocalesOf
Intl.supportedValuesOf
isFinite
isNaN
JSON
JSON.parse
JSON.stringify
Map
Map.prototype.clear
Map.prototype.delete
Map.prototype.entries
Map.prototype.forEach
Map.prototype.get
Map.prototype.has
Map.prototype.keys
Map.prototype.set
Map.prototype.values
Math
Math.abs
Math.acos
Math.acosh
Math.asin
Math.asinh
Math.atan
Math.atan2
Math.atanh
Math.cbrt
Math.ceil
Math.clz32
Math.cos
Math.cosh
Math.E
Math.exp
Math.expm1
Math.floor
Math.fround
Math.hypot
Math.imul
Math.LN10
Math.LN2
Math.log
Math.log10
Math.LOG10E
Math.log1p
Math.log2
Math.LOG2E
Math.max
Math.min
Math.PI
Math.pow
Math.random
Math.round
Math.sign
Math.sin
Math.sinh
Math.sqrt
Math.SQRT1_2
Math.SQRT2
Math.tan
Math.tanh
Math.trunc
NaN
Number
Number.EPSILON
Number.isFinite
Number.isInteger
Number.isNaN
Number.isSafeInteger
Number.MAX_SAFE_INTEGER
Number.MAX_VALUE
Number.MIN_SAFE_INTEGER
Number.MIN_VALUE
Number.NaN
Number.NEGATIVE_INFINITY
Number.parseFloat
Number.parseInt
Number.POSITIVE_INFINITY
Number.prototype.toExponential
Number.prototype.toFixed
Number.prototype.toLocaleString
Number.prototype.toPrecision
Number.prototype.toString
Number.prototype.valueOf
Object
Object.assign
Object.create
Object.defineProperties
Object.defineProperty
Object.entries
Object.freeze
Object.fromEntries
Object.getOwnPropertyDescriptor
Object.getOwnPropertyDescriptors
Object.getOwnPropertyNames
Object.getOwnPropertySymbols
Object.getPrototypeOf
Object.hasOwn
Object.is
Object.isExtensible
Object.isFrozen
Object.isSealed
Object.keys
Object.preventExtensions
Object.prototype.__defineGetter__
Object.prototype.__defineSetter__
Object.prototype.__lookupGetter__
Object.prototype.__lookupSetter__
Object.prototype.__proto__
Object.prototype.constructor
Object.prototype.hasOwnProperty
Object.prototype.isPrototypeOf
Object.prototype.propertyIsEnumerable
Object.prototype.toLocaleString
Object.prototype.toString
Object.prototype.valueOf
Object.seal
Object.setPrototypeOf
Object.values
parseFloat
parseInt
Promise
Promise.all
Promise.allSettled
Promise.any
Promise.prototype.catch
Promise.prototype.finally
Promise.prototype.then
Promise.race
Promise.reject
Promise.resolve
Proxy
RangeError
ReferenceError
Reflect
Reflect.apply
Reflect.construct
Reflect.defineProperty
Reflect.deleteProperty
Reflect.get
Reflect.getOwnPropertyDescriptor
Reflect.getPrototypeOf
Reflect.has
Reflect.isExtensible
Reflect.ownKeys
Reflect.preventExtensions
Reflect.set
Reflect.setPrototypeOf
RegExp
RegExp.prototype.compile
RegExp.prototype.exec
RegExp.prototype.test
RegExp.prototype.toString
Set
Set.prototype.add
Set.prototype.clear
Set.prototype.delete
Set.prototype.entries
Set.prototype.forEach
Set.prototype.has
Set.prototype.keys
Set.prototype.values
SharedArrayBuffer
SharedArrayBuffer.prototype.slice
String
String.fromCharCode
String.fromCodePoint
String.prototype.anchor
String.prototype.at
String.prototype.big
String.prototype.blink
String.prototype.bold
String.prototype.charAt
String.prototype.charCodeAt
String.prototype.codePointAt
String.prototype.concat
String.prototype.endsWith
String.prototype.fixed
String.prototype.fontcolor
String.prototype.fontsize
String.prototype.includes
String.prototype.indexOf
String.prototype.italics
String.prototype.lastIndexOf
String.prototype.link
String.prototype.localeCompare
String.prototype.match
String.prototype.matchAll
String.prototype.normalize
String.prototype.padEnd
String.prototype.padStart
String.prototype.repeat
String.prototype.replace
String.prototype.replaceAll
String.prototype.search
String.prototype.slice
String.prototype.small
String.prototype.split
String.prototype.startsWith
String.prototype.strike
String.prototype.sub
String.prototype.substr
String.prototype.substring
String.prototype.sup
String.prototype.toLocaleLowerCase
String.prototype.toLocaleUpperCase
String.prototype.toLowerCase
String.prototype.toString
String.prototype.toUpperCase
String.prototype.trim
String.prototype.trimEnd
String.prototype.trimStart
String.prototype.valueOf
String.raw
Symbol
Symbol.asyncIterator
Symbol.for
Symbol.hasInstance
Symbol.isConcatSpreadable
Symbol.iterator
Symbol.keyFor
Symbol.match
Symbol.matchAll
Symbol.prototype.description
Symbol.prototype.toString
Symbol.prototype.valueOf
Symbol.replace
Symbol.search
Symbol.species
Symbol.split
Symbol.toPrimitive
Symbol.toStringTag
Symbol.unscopables
SyntaxError
TypeError
Uint16Array(TypedArray)
Uint32Array(TypedArray)
Uint8Array(TypedArray)
Uint8ClampedArray(TypedArray)
undefined
unescape
URIError
WeakMap
WeakMap.prototype.delete
WeakMap.prototype.get
WeakMap.prototype.has
WeakMap.prototype.set
WeakRef
WeakRef.prototype.deref
WeakSet
WeakSet.prototype.add
WeakSet.prototype.delete
WeakSet.prototype.has
